### ISSUE TITLE
🐛 Lists that are indented are messed up 

### ISSUE THREAD

**Issue by mbercx** [executablebooks/rst-to-myst#17]
**Describe the bug**

Lists that have been indented in `.rst` are converted in such a way that they aren't rendered properly.

**To Reproduce**

When trying to convert the following `.rst` snippet:

```rest
This is a numbered list!

#. Step 1
#. Step 2
#. Step 3
#. Step 4

This is a numbered list with indentation!

    #. Step 1
    #. Step 2
    #. Step 3
    #. Step 4

This is a regular list with indentation!

    * Step 1
    * Step 2
    * Step 3
    * Step 4
```

You obtain

```
This is a numbered list!

1. Step 1
2. Step 2
3. Step 3
4. Step 4

This is a numbered list with indentation!

> > 1. Step 1
> 2. Step 2
> 3. Step 3
> 4. Step 4

This is a regular list with indentation!

> > * Step 1
> * Step 2
> * Step 3
> * Step 4
```

**Expected behavior**

The `>` should probably be removed, even though this means there is no difference between the indented and non-indented case (which is different for `.rst`).

**Environment**

- Python Version [e.g. 3.7.1]: 3.8.6
- Package versions or output of `jupyter-book --version`:
```
Sphinx 2.4.4
rst-to-myst                   0.1.2
mypy-extensions               0.4.3
myst-nb                       0.13.0a1
myst-parser                   0.14.0a2
```
- Operating System: macOS Big Sur 11.3.1

**Comment by chrisjsewell** [comment]
@mbercx have you checked how this actually renders in RST?

Because of https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#block-quotes, these indented lists will indeed be rendered as block quotes, hence the preceding `>` (which is the Markdown version of block quotes)

(although as of #18, the initial `> >` is "fixed" to only be `>`)

will close but gimme a shout if you still think it is a bug
